name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # https://github.com/actions/checkout
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Pull LFS data
        # Checkout will only fetch the data but will not expand the files
        run: git lfs pull

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npx oxlint --error-on-warnings

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install Playwright browsers
        # Takes about 2...3 minutes
        run: npx playwright install --with-deps --only-shell

      - name: Run Playwright tests
        run: npm test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results
          path: |
            test-results/
            playwright-report/
          retention-days: 30
